apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-address-pool
  namespace: metallb-system
spec:
  addresses:
    - 54.38.190.139/32
  autoAssign: true
  avoidBuggyIPs: true
