---
- name: Add metallb helm repo
  command: helm repo add --force-update metallb https://metallb.github.io/metallb
  changed_when: false

- name: Check if metallb release exists
  command: helm status metallb -n metallb-system
  register: metallb_status
  failed_when: false
  changed_when: false

- name: Install metallb
  command: >-
    helm upgrade --install metallb metallb/metallb
    --namespace metallb-system
    --create-namespace
    --wait
  when: metallb_status.rc != 0
