---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCYz2RFQR8piPaESf5i0MaGK6AIRSy7UNbEWfV39CKi/7/layNJLMgw8xLK2ASpTUVWcb6KBPCDb3NdxOGQJzdwlK55iGyECtmIRv6qI8mnKiwsZmCx7L0gSjkT5RcDtZCf9JIN0h/u7yL7eeyug9u+kMCZVFywWsODLMd28drdAqgZi1SVN3RCysI8kNKwQ4CmGHPJqrPwdQIP5OEK3fnJS4JapEJ2cni6kk2h6MgBlU5L/HP1tUWyP+Wiwo4jB8MWyLc2DJ/aloc4z4ClGkq65CBnoKQ0D31LR+RsgMwyov4Mw0fNtJVdifLzcrSksORFA1cC7r4nt49RI31e8kr6xwiK5yzu19JXJA9N+brLmn4y9S7nWM3mhNngLWVZn8ZAXO3+FQDO3t4xwloH/Qc8XCbI6VeEYzXVhaPbxcUTJmeiDXioyA2w5MlGxxU86bpcQE4CxxtWG52TsHJQZwtHY/BpiPjS/hlmePfJyaMqTja5HnzVGh4Jbd5Gr4P46BJwM0PeTl8dMObhgzKQEJt+PCiE6Yty141N65KX9v6ci9gV3UcvDYHKOuprdKxDlKzXe2TY8qblOL4vLVar63OIrJbO5Cko9dWjOuDvFd4r4M25MZ0vKhc0BpavvaMIeODW7rh1iXqnOTMjCBZp33ufuhNwRBn3pw9/BWTalblf2xd/tApjRMcIumeRPZIEkx/EAo3QrHWkfdrkcuHlU9dvZ7kExCM7l6I=
    admin-user: AgCcol3mKbXiLSk/ySAph0bc95mijK4lZXfxe6YLz62cNdVYaM/HbUpXBlJfNpbo6Q4avA7PjsNr76R08N80oB2SUhCrH3QfCu9h+ZM6CZFu8HM5fjpn/TouZSmMionRXrpIUT4M9wWPYPbd3zEnghGYcT8JLPSyQgHJTAXILG1DSc2c/OPLaoBQLP+s2hoe5GPYNF0+zoshrUsCYjEPOXy6zYYxZOCJ7H2ehprmqJ1kgd/LDa6wQLyoNRcdmdzoKdxUYz5e/WIlUjT2L+iy5Uh8DEwrFacee1ghhs4H4q55FMMH0VdX8zuOua4LmEBPXTa2fToeiZaY7GLpJxJnAJB1RO9Do55Ck8IfAKPlEcVEm7BRzi22ME4AsysNsrUovv4asBLQGXjmSsakwiFWKvf+iceS2UgIQCP15liGSUUc2qmKskGRCKBIl1+FvEYTxiv+ZgKyyU65LIJ4kx9U9SyA7FFj/RXI3XD5NdO4n4Sd5Pzwi+xAe6wPYlid9UEaYqKTqZh95USmjBeoK50dwP5pmKJeUD3PmjW0BN8e501P/JnZUFlo0do7CU6VG0mnZzYAG1/QNKCMOPwT38RyJH+WxLipxdAsSTI27OH1nFRyN/37EHICMKLwv1aDyTT8ilUhSKvAzN2k4V8892+TszXXVdyvpP6bB4FRB4SGW+7B48uzb5Shq8eLplpHHubVQUFGwgPymw==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
    type: Opaque
