---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgCr2harzjeJbHYGdnaf2LGrTrmdFT4uCEpPUJIZOwfQ4JJBPoo8mQvzKAYK1WRKJeDcMRv/8+PQpPJKYuGZp0RCqVbtEUGutWTAMiaAzNenhvWTKZ8VycO/mjf5t7bcEPDni28NdfnOMlC0splBEAYkxjedBe3yfXDeCV8rAAhCuuHJvbpIYeZxbXKk0WgSlsFry6Y0vXeuefRsbik86/QqoM5EVqejquTnNqB0bt+GNhfUbeSPTLdx+QN9HK+ZMaC3RrIQ4Gyb58LfqsOnEJNEO6s4yvtidwKP21ZNqxv+ucz9jchEZdDz3AyCju+wuex6Z0rpxRbGp0g1Fp3chVfpAe0VsFMnmIgaLFUyEf1gVH3yna1Ief2DUl3EPedhgqBNkyXy9T6b5h08SoNWzzwQyKTcgN/a51FrYiBODs8HZyd/rvSDxoI/SQUPNXAWxy/S5U4pxWNUysxBprj5278ctY8lQdrdhudtPvBeeHf4KK95eWoCeAKYXaDCK5y0LxgyTd0TrPy9bJF1i1RyECP1zIMSTsjxoB3St6XUnTzdSMHSa/pIrMaxSSh2MJPukav8TxRldIRhhZwLFqJnl+e5gUryE+W53zs6jvJSEJcTTkf07ARowKGf80Rrn1Cwb6c2HTMvr1zaBHAGlGHk00mc917HJ6aUA7sjIqN5L1xHbQBeleaOQhKN4DSv+TO9EsBj9dZ/SzwgIueKA8ubnQy/iA==
    client_secret: AgBPA1Lps3Jr24qpPvgIHy9ReIhZa/0urBJBWbJhqNPZR+WzkqJIzCRFYPz/bsQmUYZWva+6OMh5XRS5SWGDHdcPgVV7AfHG7myMLxtD9+KVnJbfn2zKpM0WMjpGH6C4yx8OVB4DIyqHS3p+x51cBSZKOqEWu78EmiPNbWNqPaegnNSJ6Bw2ArWtjzf2/y+5E3cc4/bV7dE5R3JjX3TmoN7JF8I0+oMQU7DIy21mdqMLI3/11ZWBEqDGO2Jo3Xh+sLYp6IyXndfIt3U4raESUIaUF6OMiMKgJ3+FYhw15nZQLQfga7McDRa4R6NnhwL83gRwltr0AoFX5HAMr2UGb6OAeiR3CerPTiB8VsSpfehYBQq5D7R6Dy8ko3tP53xk+83TwIxr/Rb7tMvS8qbv3zF7KrgOtFbpMACvORfLTjYJjFkPEA++5HivHsqQD/z7y42MazW3grYLi9Q4/Kbwxg+5Oo9S3GjufeBELChUWSjpUT/t6TJODz9MpYDdL7c0c2KQSCy2XRuHov7rFtyqyx0laKJ+3Jye00hXJrp4jdWM/cnk//QOwA7wMTxhcKiHC1wZLhPsCAnGMOTg5KkDC76MxAL1DeFV2Hc+BwiHTzT5tUFBhNTYvXdwl2aAck6fPZTCtKGm3C/2L3CFMWbppJdizI6lwd0qpS2g0CYA1MrCxEKijDsfRysgg2aHEHUTGyEW6mZR8pDpJ8mQkDVTJu2gtaeMQr8ae5VDBmvdYo40ob/sT0sazFZByJsTxrWHz8q+avM9gIxy1evmicwLglE=
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
