---
- name: Install k3s
  shell: curl -sfL https://get.k3s.io | sh -s - --disable traefik
  args:
    creates: /usr/local/bin/k3s

- name: Install helm
  shell: curl -sfL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  args:
    creates: /usr/local/bin/helm

- name: Install Envoy Gateway
  shell: helm upgrade --install eg oci://docker.io/envoyproxy/gateway-helm --version v1.7.2 -n envoy-gateway-system --create-namespace
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml

- name: Wait for Envoy Gateway to be available
  shell: kubectl wait --timeout=5m -n envoy-gateway-system deployment/envoy-gateway --for=condition=Available
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
