---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-secrets
  namespace: nextcloud
spec:
  encryptedData:
    nextcloud-password: AgAGSBnzYy5ve8DVX8sqCVix2KkNZ7GSU7iTB1QO7okqp1kA1hkE6ikh84QhhyI7tDagtxJdtcEfjPdrSBNo4LPEPnYGduLT4s2IBKAdfWTBrSN7x/pKHk7nuSkTcQGQOq2SBODzi1ogwfdNu4Jdk1Ee1bGho17MFWFCsKlDjfanDiA46LWQ/gpSoBXIrqpZIpazI6irCTZOJ/dVrh9nRYGAauUTYeY1PSLyOsXWaDoOSzvg7hRSYuEzBCDyFjWbgGJebv15MUiMdS6kG1Bk/wns/IuKoL1Mi22DIVCdibDVGtRfLQduqu4j2ehfDv+gmDupUjWMQHeOXfU0EEBgE6aS3HhUT9TrL/poQ7BdTQuqgsM9MYhiR5LnXqCzoVVhpK9xIfOpXtyTrI9EQcHXyZK8oO8hisy0WGYD7azSjpaMF+zvnS9HOr6WMBT59Lh7OkrF8hAOGslns/YNqSydY2tiWfnFT/DB7nx1xa+be/JI0S24tPncuvt6jLn1Q3BphQHtAUcOW8UYg9Z4JSmmuObIPXJZ4lo0Q9/v6U2tQOzQiVVoBvoZfDoxnWDa1WPVkmVxMHmQvE70soiAJTYd53RMh9/R+iK2iSK/rsD2X+tiZLsa4v9TjeUFdneCDKM5BSzjZmkBfCLUroTZCvAwS3rSXbbh1Pg/0M3tHsxWYZtdPVFslkajzRW5W3z0I4SwmTuw48UFfA87evbfikR/F/6xL9iDQ/sdqzI=
    nextcloud-username: AgB25x8BJCZU3+hLUXVEthjPDyjDuuZyG4EQn9bunsJX2HaWIelMAEClVdW8vs1YQFjgVMrZ6RyQBmSi5Daivyp5vgGyTw2r4E3ce7rpEmu3mpK5jCGgfsHgjDHhtTpkCyAUzayPqnbMk/Kj1fgNdUIBB2oVil8s76nrIhQnDUImfhp2ukPBIYPK0tRdJQSpx4zJGJQxAINaXuX2E2N6AgKd9AJreOpOHZE23nT3dmSSkzyckB7vn9X0fDXM2q4Wtev33hV1mmPMPh+IToBt5/k7UP4tAwel2q6hYPYC84OMJWD6AM0ErQzQ+/VYBCwtNbHFhfOTYU54C9wzOLWOFrUZDUHEq3fAGRWSN8VFry1ib8cz08Lph9KAFSHYhq0RtP4Wyp4bgRM/3ci6y5MHOcYNtWz47GK1mMZ5YHhjAXt62da0L6fG/u1GQhW/tUrHb7w3AKZezpm7DiFCOSFzKJlKMXfckTxaJlgRRWY8cV+lgLxUAbX3XGrG+WrdmptqJ/FkUf1yDF9SyPnYX+l1yeuWlQX/WsqzlL4H+RDN8OPl9b349IiM/rMjh/oHEnSc2C1nynwMhsCUKDUuwrvvj4VgJerO/tEKOyFLjQrQfuShrNcWthCVj4KAJZxlp6A1KZzpN9bRy16VAT/0dvOtXwmOO0N+oOrWpSTgxJ4dFYTyyPdgqFCmwmhfF+9feIWYrleXkA0kLQ==
  template:
    metadata:
      name: nextcloud-secrets
      namespace: nextcloud
    type: Opaque
