---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pomopensource-secrets
  namespace: pomopensource
spec:
  encryptedData:
    APP_KEY: AgCORysgLlm0My28XAJ7psaCkE3YMuqLQz3bVDkaMFXs63cQ1oSJG6+Y4NAjvUOTErvn6Ee07b1A5Qmo/HMTLJY++2RBpEzIBnS+iPi/u66ZmQzsuJ9TewUD4Thf/lX+YDn/PwsTgTaN6XxboPr+k1mOWMwTy4fB4ZOG8PbmmlHMOkI1hXuK39ahsRG46y0uE4kZ1CFsNle3tlkZ6sUEdVCU9moza/lYjmtybj6zrmJhnb7LV4Nf94YP3iKWJe6SLQb5qXKMcPw9z0C6CPudVBBhH16ivr4wBUNhsnOVnnit/l3bAplPHVH0POx3o37YUvNj0A3Q2ehnZjzXVFJYiw50cDU3D3xfs47oNSMn1Y8xqUhTuGAqbEumjvyHfCuxB34REiH2e+6HoO0YecMDKS9dUcC7SImmhTLAwghaluSM9EzmS6w0vb2Z2zkAsi0ZoAIE/4UZWWJASsV8lv/+XNaGwRa5cKmMIyek56cot+jrM1SRRIOqF0u0PxVTMipXkZv8cGmBPlFJBPdwmYvBjzKtPgaK4D6F0U1xwXG4rddJw26rrU3pCmtMo1jJAfPlvX3Se+aAQvDncB0DUTmhr5d88vN8wor2GBXhxQIw2h/sBwhPFyoR1SJ5aR+r+R1/c9HuQTbsN3qErZRAi/AEDXs6tYnUKkOOcTKDztbdHaLHXIEk+3983NYcBt43jf0t4NYLdElkCo3t+z6KUDj/X7BIhtBC/DW6DR8beOaeXkGm+2twILudPuUmlHEaGWoIpD8DrVs=
  template:
    metadata:
      name: pomopensource-secrets
      namespace: pomopensource
