apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zeina
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - repoURL: ghcr.io/corentin-dupaigne/zeina/charts
      chart: zeina
      targetRevision: 0.1.0
      helm:
        values: |
          hostname: "girlfriend.corentindupaigne.com"
          gateway:
            name: default-gateway
            namespace: kube-system
  destination:
    server: https://kubernetes.default.svc
    namespace: zeina
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
